#!/usr/bin/env python3
"""Vendor KaTeX's stylesheet and fonts out of node_modules into src/.

    npm run vendor:katex

Re-run after bumping the katex version in package.json. Nothing here runs in the
browser; the output it writes is what ships — src/styles/katex.css and
src/assets/fonts/katex/ are committed, so the build needs neither Python nor this
script, only the checked-in result.

Why this exists rather than `import 'katex/dist/katex.min.css'`: that import
works, but it drags all 60 font files (woff2 + woff + ttf, 1,080,668 B) into
dist/, and pins the @font-face rules to whatever upstream ships. Two changes are
worth making on the way through:

  * woff2 only. The woff and ttf branches are 76% of those bytes and exist for
    IE11/Android 4; every engine that runs this site supports woff2.
  * The url() has to be repointed at src/assets/fonts/katex/ so Vite hashes and
    fingerprints the fonts like every other asset.

Upstream's own font-display: block is checked rather than set, and is
deliberately the opposite of the site's body font. Atkinson uses swap because a
paragraph in the fallback face is readable while the real one arrives. A formula
in the fallback face is not: the fallback has no glyph for ∑ or a size-4 brace,
so swap paints tofu, and KaTeX positions every span from the real font's
metrics, so the correction reflows the formula. Better a brief blank than a
wrong formula that jumps. (block falls back after ~3s, so a font that never
arrives still degrades rather than hiding the maths forever.)

All 20 faces are kept even though the site's formulas touch far fewer. They cost
nothing to a reader — @font-face downloads on demand, and e2e/katex.spec.ts pins
what a math page actually fetches — while a missing math glyph is a hole in an
equation, not the graceful system-font substitution a missing text glyph gets.
"""

import os
import re
import shutil
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_CSS = os.path.join(ROOT, 'node_modules/katex/dist/katex.min.css')
SRC_FONTS = os.path.join(ROOT, 'node_modules/katex/dist/fonts')
DST_CSS = os.path.join(ROOT, 'src/styles/katex.css')
DST_FONTS = os.path.join(ROOT, 'src/assets/fonts/katex')

# Where the rewritten url() has to point, relative to DST_CSS. Vite resolves it
# at build time and emits the font under dist/_astro/ with a content hash.
FONT_URL_PREFIX = '../assets/fonts/katex/'

HEADER = """/* Generated by scripts/build-katex-css.py from node_modules/katex@{version} -- do not edit.
 * KaTeX is MIT licensed; see src/assets/fonts/katex/LICENSE.
 * woff2-only @font-face (upstream also lists woff and ttf); font-display: block is upstream's.
 */
"""


def katex_version():
    pkg = os.path.join(ROOT, 'node_modules/katex/package.json')
    with open(pkg, encoding='utf-8') as fh:
        for line in fh:
            m = re.search(r'"version"\s*:\s*"([^"]+)"', line)
            if m:
                return m.group(1)
    return 'unknown'


def rewrite(css):
    """Drop the woff/ttf src entries and repoint woff2 at src/assets/."""
    # src:url(fonts/X.woff2) format("woff2"),url(fonts/X.woff) format("woff"),
    #     url(fonts/X.ttf) format("truetype")
    css, legacy = re.subn(
        r',url\(fonts/[^)]+\.(?:woff|ttf)\)\s*format\("(?:woff|truetype)"\)', '', css
    )
    css, kept = re.subn(r'url\(fonts/', f'url({FONT_URL_PREFIX}', css)
    faces = css.count('@font-face{')
    if kept != faces:
        sys.exit(f'error: {faces} faces but {kept} woff2 urls -- upstream layout changed')
    # Upstream ships block on every face (see the module docstring for why that
    # is right here); if it ever changes, the tradeoff needs a human, not a
    # silent rewrite.
    blocked = len(re.findall(r'font-display:\s*block', css))
    if blocked != faces:
        sys.exit(
            f'error: {blocked} of {faces} faces set font-display:block -- '
            'upstream changed it; decide before shipping'
        )
    return css, faces, legacy


def main():
    if not os.path.exists(SRC_CSS):
        sys.exit('error: node_modules/katex missing -- run `npm install` first')

    with open(SRC_CSS, encoding='utf-8') as fh:
        original = fh.read()
    css, faces, legacy = rewrite(original)

    os.makedirs(os.path.dirname(DST_CSS), exist_ok=True)
    with open(DST_CSS, 'w', encoding='utf-8') as fh:
        fh.write(HEADER.format(version=katex_version()))
        fh.write(css)
        if not css.endswith('\n'):
            fh.write('\n')

    # Fonts referenced by the rewritten css, so a face dropped upstream stops
    # being copied instead of lingering as an orphan.
    wanted = sorted(set(re.findall(re.escape(FONT_URL_PREFIX) + r'([^)]+\.woff2)', css)))
    if os.path.isdir(DST_FONTS):
        shutil.rmtree(DST_FONTS)
    os.makedirs(DST_FONTS)
    total = 0
    for name in wanted:
        shutil.copy2(os.path.join(SRC_FONTS, name), os.path.join(DST_FONTS, name))
        total += os.path.getsize(os.path.join(DST_FONTS, name))
    shutil.copy2(os.path.join(ROOT, 'node_modules/katex/LICENSE'), os.path.join(DST_FONTS, 'LICENSE'))

    upstream_fonts = sum(
        os.path.getsize(os.path.join(SRC_FONTS, f)) for f in os.listdir(SRC_FONTS)
    )
    print(f'katex {katex_version()}')
    print(f'  css    {len(original):6} B -> {os.path.getsize(DST_CSS):6} B  '
          f'({faces} faces, {legacy} woff/ttf src dropped)')
    print(f'  fonts  {upstream_fonts:7} B -> {total:6} B  ({len(wanted)} woff2 kept)')


if __name__ == '__main__':
    main()
