// HTTP status code reference (RFC 9110 + widely-deployed additions), consumed
// by the devtools/http-status-lookup text tool. Pure data, no DOM.
export interface StatusEntry {
	code: number;
	category: '1xx' | '2xx' | '3xx' | '4xx' | '5xx';
	name: string;
	nameZh: string;
	meaning: string;
	meaningZh: string;
	cause: string;
	causeZh: string;
}
export const HTTP_STATUSES: StatusEntry[] = [
	{ code: 100, category: '1xx', name: 'Continue', nameZh: '继续', meaning: 'The client should continue with the request body; used with the Expect: 100-continue header.', meaningZh: '客户端应继续发送请求体；与 Expect: 100-continue 头配合使用。', cause: 'Client asks "may I send a large body?" before uploading.', causeZh: '客户端在上传大请求体前先行探询。' },
	{ code: 101, category: '1xx', name: 'Switching Protocols', nameZh: '切换协议', meaning: 'The server agrees to switch protocols; almost always WebSocket via the Upgrade header.', meaningZh: '服务器同意切换协议；几乎总是通过 Upgrade 头升级到 WebSocket。', cause: 'WebSocket handshake request.', causeZh: 'WebSocket 握手请求。' },
	{ code: 103, category: '1xx', name: 'Early Hints', nameZh: '早期提示', meaning: 'Sent before the final response so the browser can preload assets (Link headers).', meaningZh: '在最终响应前先行发送，让浏览器预加载资源（Link 头）。', cause: 'Server wants the client to fetch CSS/JS before HTML is ready.', causeZh: '服务器希望客户端在 HTML 就绪前先取 CSS/JS。' },
	{ code: 200, category: '2xx', name: 'OK', nameZh: '成功', meaning: 'The request succeeded; the meaning of the body depends on the method (GET returns it, PUT confirms).', meaningZh: '请求成功；响应体的含义取决于方法（GET 返回资源，PUT 确认更新）。', cause: 'Everything worked.', causeZh: '一切正常。' },
	{ code: 201, category: '2xx', name: 'Created', nameZh: '已创建', meaning: 'The request created a new resource; the Location header points to it.', meaningZh: '请求创建了新资源；Location 头指向它的地址。', cause: 'Successful POST that inserts a record.', causeZh: 'POST 成功插入一条记录。' },
	{ code: 202, category: '2xx', name: 'Accepted', nameZh: '已接受', meaning: 'The request is queued for processing but not finished yet.', meaningZh: '请求已入队处理但尚未完成。', cause: 'Async jobs: video encoding, batch imports.', causeZh: '异步任务：视频转码、批量导入。' },
	{ code: 204, category: '2xx', name: 'No Content', nameZh: '无内容', meaning: 'Success with an empty body — the classic DELETE or PUT response.', meaningZh: '成功但响应体为空——DELETE/PUT 的典型响应。', cause: 'Deletion finished; nothing to return.', causeZh: '删除完成，无需返回内容。' },
	{ code: 206, category: '2xx', name: 'Partial Content', nameZh: '部分内容', meaning: 'Only part of the resource is returned, per the Range header — how video seeking and download resumption work.', meaningZh: '按 Range 头只返回资源的一部分——视频拖动进度条与断点续载的基础。', cause: 'Range request from a media player or download manager.', causeZh: '播放器或下载器的分段请求。' },
	{ code: 301, category: '3xx', name: 'Moved Permanently', nameZh: '永久重定向', meaning: 'The resource has a new permanent URL; browsers and search engines cache it.', meaningZh: '资源有了新的永久地址；浏览器与搜索引擎会缓存。', cause: 'Domain migration, HTTP→HTTPS, URL restructure.', causeZh: '域名迁移、HTTP→HTTPS、URL 结构调整。' },
	{ code: 302, category: '3xx', name: 'Found', nameZh: '临时重定向', meaning: 'Temporary redirect — the original URL stays canonical. Historically abused, so 303/307 exist for precision.', meaningZh: '临时重定向——原 URL 仍是规范地址。历史上被滥用，因此有了更精确的 303/307。', cause: 'Login-then-return flows, A/B routing.', causeZh: '登录后跳回、A/B 分流。' },
	{ code: 303, category: '3xx', name: 'See Other', nameZh: '参见其他', meaning: 'Redirect with an explicit instruction: fetch the target with GET, whatever the original method was.', meaningZh: '重定向并明确指示：无论原方法是什么，都用 GET 取目标。', cause: 'POST-then-show-page pattern (PRG).', causeZh: '提交后展示页面（PRG 模式）。' },
	{ code: 304, category: '3xx', name: 'Not Modified', nameZh: '未修改', meaning: 'The cached copy is still fresh (validated via If-None-Match / If-Modified-Since) — no body is sent.', meaningZh: '缓存副本仍然新鲜（经 If-None-Match / If-Modified-Since 校验）——不发送响应体。', cause: 'Conditional request with a matching ETag.', causeZh: '带匹配 ETag 的条件请求。' },
	{ code: 307, category: '3xx', name: 'Temporary Redirect', nameZh: '临时重定向（保方法）', meaning: 'Like 302 but the method and body must be repeated unchanged at the new URL.', meaningZh: '类似 302，但要求以原方法与请求体原样重发到新地址。', cause: 'Redirecting a POST form without losing its data.', causeZh: '重定向 POST 表单而不丢数据。' },
	{ code: 308, category: '3xx', name: 'Permanent Redirect', nameZh: '永久重定向（保方法）', meaning: 'Like 301 but the method and body must be repeated — the strict, modern permanent redirect.', meaningZh: '类似 301，但要求原样重发方法与请求体——严格意义上的现代永久重定向。', cause: 'Permanent API endpoint moves.', causeZh: 'API 端点永久迁移。' },
	{ code: 400, category: '4xx', name: 'Bad Request', nameZh: '错误请求', meaning: 'The server cannot understand the request — malformed syntax, invalid framing, or impossible routing.', meaningZh: '服务器无法理解请求——语法错误、报文格式非法或路由不可能。', cause: 'Malformed JSON, wrong Content-Length, bad URL encoding.', causeZh: 'JSON 格式错、Content-Length 不符、URL 编码错误。' },
	{ code: 401, category: '4xx', name: 'Unauthorized', nameZh: '未认证', meaning: 'Authentication is required (or failed). Should carry WWW-Authenticate. Not about permissions — that is 403.', meaningZh: '需要认证（或认证失败）。应附带 WWW-Authenticate。与权限无关——那是 403。', cause: 'Missing/expired token, no login session.', causeZh: '令牌缺失/过期、未登录。' },
	{ code: 402, category: '4xx', name: 'Payment Required', nameZh: '需要付费', meaning: 'Reserved for future use; in practice some APIs use it for quota-billing states.', meaningZh: '为未来用途保留；实践中一些 API 用于配额计费状态。', cause: 'Nonstandard — API-specific.', causeZh: '非标准——具体 API 自定义。' },
	{ code: 403, category: '4xx', name: 'Forbidden', nameZh: '已禁止', meaning: 'The server understood you, knows who you are, and still refuses. Authentication will not help.', meaningZh: '服务器认识你，但依然拒绝。认证也不会有帮助。', cause: 'Insufficient permissions, IP blocked, file permissions.', causeZh: '权限不足、IP 被封、文件系统权限。' },
	{ code: 404, category: '4xx', name: 'Not Found', nameZh: '未找到', meaning: 'The server found no resource at this URL. The most famous status code on the web.', meaningZh: '服务器在该 URL 下找不到资源。全网最出名的状态码。', cause: 'Dead link, typo, deleted record.', causeZh: '死链、拼写错误、已删除的记录。' },
	{ code: 405, category: '4xx', name: 'Method Not Allowed', nameZh: '方法不允许', meaning: 'The URL exists but not for this HTTP method. The response must list allowed methods in Allow.', meaningZh: 'URL 存在但不支持该 HTTP 方法。响应必须在 Allow 中列出可用方法。', cause: 'PUT to a read-only endpoint.', causeZh: '对只读端点发 PUT。' },
	{ code: 406, category: '4xx', name: 'Not Acceptable', nameZh: '不可接受', meaning: 'No content can be produced matching the Accept header the client sent.', meaningZh: '无法生成符合客户端 Accept 头的内容。', cause: 'Client demands only application/xml, server speaks JSON.', causeZh: '客户端只要 application/xml，服务器只说 JSON。' },
	{ code: 408, category: '4xx', name: 'Request Timeout', nameZh: '请求超时', meaning: 'The client took too long to send the request; the server gave up waiting.', meaningZh: '客户端发送请求太慢，服务器放弃等待。', cause: 'Slow upload, stalled connection.', causeZh: '上传过慢、连接停滞。' },
	{ code: 409, category: '4xx', name: 'Conflict', nameZh: '冲突', meaning: 'The request conflicts with the current state of the resource.', meaningZh: '请求与资源当前状态冲突。', cause: 'Duplicate create, stale edit (no optimistic locking).', causeZh: '重复创建、旧版本编辑（缺乐观锁）。' },
	{ code: 410, category: '4xx', name: 'Gone', nameZh: '已删除', meaning: 'Like 404 but deliberate: the resource was removed permanently and the URL should be forgotten.', meaningZh: '类似 404 但属有意为之：资源已永久移除，该 URL 应被遗忘。', cause: 'Discontinued products, deliberately retired URLs.', causeZh: '下架产品、有意废弃的 URL。' },
	{ code: 412, category: '4xx', name: 'Precondition Failed', nameZh: '前置条件失败', meaning: 'A condition the client set (If-Match / If-Unmodified-Since) evaluated to false.', meaningZh: '客户端设定的条件（If-Match / If-Unmodified-Since）不成立。', cause: 'Optimistic concurrency check failed.', causeZh: '乐观并发校验失败。' },
	{ code: 413, category: '4xx', name: 'Content Too Large', nameZh: '内容过大', meaning: 'The request body exceeds what the server accepts.', meaningZh: '请求体超过服务器接受的上限。', cause: 'Upload limit (nginx client_max_body_size, framework limits).', causeZh: '上传上限（nginx client_max_body_size、框架限制）。' },
	{ code: 415, category: '4xx', name: 'Unsupported Media Type', nameZh: '不支持的媒体类型', meaning: 'The body format is not supported — check Content-Type.', meaningZh: '请求体格式不受支持——检查 Content-Type。', cause: 'Sending form-data to a JSON-only endpoint, or vice versa.', causeZh: '给 JSON 端点发 form-data，或反之。' },
	{ code: 418, category: '4xx', name: "I'm a teapot", nameZh: '我是茶壶', meaning: 'An April Fools joke (HTCPCP) that became official RFC culture: the server refuses to brew coffee because it is a teapot.', meaningZh: '愚人节玩笑（HTCPCP）成为 RFC 官方文化：服务器是茶壶，拒绝煮咖啡。', cause: 'Easter egg; some APIs use it for rate-limit teases.', causeZh: '彩蛋；个别 API 拿它开限流玩笑。' },
	{ code: 422, category: '4xx', name: 'Unprocessable Content', nameZh: '内容无法处理', meaning: 'The syntax is valid but the semantics fail — the classic validation error response.', meaningZh: '语法合法但语义不通过——典型的表单校验错误响应。', cause: 'Failing field validation on an otherwise well-formed JSON body.', causeZh: 'JSON 结构正确但字段校验不过。' },
	{ code: 425, category: '4xx', name: 'Too Early', nameZh: '为时尚早', meaning: 'The server refuses a replayable request to avoid replay attacks on eventual-consistency systems.', meaningZh: '服务器拒绝可重放的请求，以防最终一致性系统上的重放攻击。', cause: 'Replay protection windows.', causeZh: '重放保护窗口。' },
	{ code: 428, category: '4xx', name: 'Precondition Required', nameZh: '需要前置条件', meaning: 'The server demands conditional headers (If-Match) to avoid lost updates.', meaningZh: '服务器要求条件头（If-Match）以避免更新丢失。', cause: 'Server enforcing optimistic concurrency.', causeZh: '服务器强制乐观并发。' },
	{ code: 429, category: '4xx', name: 'Too Many Requests', nameZh: '请求过多', meaning: 'Rate limit hit. A correct response sends Retry-After.', meaningZh: '触发限流。规范的响应应带 Retry-After。', cause: 'API quotas, scraping too fast.', causeZh: 'API 配额、抓取过快。' },
	{ code: 431, category: '4xx', name: 'Request Header Fields Too Large', nameZh: '请求头过大', meaning: 'One header (or the whole header block) exceeds limits — often a cookie avalanche.', meaningZh: '单个请求头（或整个头部）超限——常见于 cookie 越积越多。', cause: 'Years of accumulating cookies past the ~8 KB header cap.', causeZh: '多年累积的 cookie 超过约 8 KB 头上限。' },
	{ code: 451, category: '4xx', name: 'Unavailable For Legal Reasons', nameZh: '因法律原因不可用', meaning: 'The resource is blocked for legal reasons (censorship, licensing); often paired with a block page.', meaningZh: '资源因法律原因被屏蔽（审查、授权）；常配合阻断页。', cause: 'Geo-blocking, GDPR takedowns, court orders.', causeZh: '地域封锁、GDPR 下架、法院指令。' },
	{ code: 500, category: '5xx', name: 'Internal Server Error', nameZh: '服务器内部错误', meaning: 'The server broke while handling the request — the catch-all for unhandled exceptions.', meaningZh: '服务器处理请求时出错——未捕获异常的兜底码。', cause: 'Unhandled exception, null reference, bad deploy.', causeZh: '未捕获异常、空引用、错误部署。' },
	{ code: 501, category: '5xx', name: 'Not Implemented', nameZh: '未实现', meaning: 'The server does not support the method or feature at all.', meaningZh: '服务器完全不支持该方法或特性。', cause: 'Server never implemented this method.', causeZh: '服务器从未实现该方法。' },
	{ code: 502, category: '5xx', name: 'Bad Gateway', nameZh: '网关错误', meaning: 'A proxy/gateway got an invalid response from the upstream server.', meaningZh: '代理/网关从上游服务器收到无效响应。', cause: 'Upstream crashed or returned garbage; classic after a bad deploy behind nginx.', causeZh: '上游崩溃或返回乱码；nginx 背后坏部署的经典症状。' },
	{ code: 503, category: '5xx', name: 'Service Unavailable', nameZh: '服务不可用', meaning: 'The server is temporarily unable to serve — overloaded or down for maintenance.', meaningZh: '服务器暂时无法服务——过载或维护中。', cause: 'Deploy in progress, traffic spike, dependency outage.', causeZh: '部署中、流量尖峰、依赖故障。' },
	{ code: 504, category: '5xx', name: 'Gateway Timeout', nameZh: '网关超时', meaning: 'The proxy did not receive a response from upstream in time. Unlike 502, upstream said nothing at all.', meaningZh: '代理未在时限内收到上游响应。与 502 不同：上游什么都没回。', cause: 'Slow upstream (DB lock, infinite loop) behind a proxy.', causeZh: '代理背后上游太慢（数据库锁、死循环）。' },
	{ code: 505, category: '5xx', name: 'HTTP Version Not Supported', nameZh: 'HTTP 版本不支持', meaning: 'The protocol version of the request is not supported by the server.', meaningZh: '服务器不支持请求的协议版本。', cause: 'Extremely rare in practice.', causeZh: '实践中极罕见。' },
	{ code: 507, category: '5xx', name: 'Insufficient Storage', nameZh: '存储不足', meaning: 'The server cannot store the representation needed to complete the request (WebDAV).', meaningZh: '服务器无法存储完成请求所需的表示（WebDAV）。', cause: 'Disk full on a WebDAV server.', causeZh: 'WebDAV 服务器磁盘满。' },
	{ code: 511, category: '5xx', name: 'Network Authentication Required', nameZh: '需要网络认证', meaning: 'The client must authenticate with the network first (captive portal / hotel Wi-Fi).', meaningZh: '客户端须先通过网络认证（强制门户 / 酒店 Wi-Fi）。', cause: 'Captive portals intercepting requests.', causeZh: '强制门户拦截请求。' },
];
