// Common extension ↔ MIME mappings (IANA registered + web-practical), consumed
// by the devtools/mime-type-lookup text tool. Pure data, no DOM.
export const MIME_MAP: { ext: string; mime: string; note?: string; noteZh?: string }[] = [
	{ ext: 'html', mime: 'text/html', note: 'always with charset', noteZh: '必须带 charset' },
	{ ext: 'htm', mime: 'text/html' },
	{ ext: 'css', mime: 'text/css' },
	{ ext: 'js', mime: 'text/javascript', note: 'not application/javascript', noteZh: '不再是 application/javascript' },
	{ ext: 'mjs', mime: 'text/javascript' },
	{ ext: 'json', mime: 'application/json' },
	{ ext: 'jsonld', mime: 'application/ld+json' },
	{ ext: 'xml', mime: 'application/xml' },
	{ ext: 'txt', mime: 'text/plain' },
	{ ext: 'md', mime: 'text/markdown' },
	{ ext: 'csv', mime: 'text/csv' },
	{ ext: 'tsv', mime: 'text/tab-separated-values' },
	{ ext: 'ics', mime: 'text/calendar' },
	{ ext: 'svg', mime: 'image/svg+xml' },
	{ ext: 'png', mime: 'image/png' },
	{ ext: 'jpg', mime: 'image/jpeg', note: 'jpeg/jpg/jfif all map here', noteZh: 'jpeg/jpg/jfif 都映射到这里' },
	{ ext: 'jpeg', mime: 'image/jpeg' },
	{ ext: 'gif', mime: 'image/gif' },
	{ ext: 'webp', mime: 'image/webp' },
	{ ext: 'avif', mime: 'image/avif' },
	{ ext: 'ico', mime: 'image/vnd.microsoft.icon', note: 'image/x-icon also common', noteZh: 'image/x-icon 也很常用' },
	{ ext: 'bmp', mime: 'image/bmp' },
	{ ext: 'tiff', mime: 'image/tiff' },
	{ ext: 'mp3', mime: 'audio/mpeg' },
	{ ext: 'wav', mime: 'audio/wav' },
	{ ext: 'ogg', mime: 'audio/ogg' },
	{ ext: 'flac', mime: 'audio/flac' },
	{ ext: 'm4a', mime: 'audio/mp4' },
	{ ext: 'opus', mime: 'audio/opus' },
	{ ext: 'mp4', mime: 'video/mp4' },
	{ ext: 'webm', mime: 'video/webm' },
	{ ext: 'mov', mime: 'video/quicktime' },
	{ ext: 'avi', mime: 'video/x-msvideo' },
	{ ext: 'mkv', mime: 'video/x-matroska' },
	{ ext: 'mpeg', mime: 'video/mpeg' },
	{ ext: 'woff', mime: 'font/woff' },
	{ ext: 'woff2', mime: 'font/woff2' },
	{ ext: 'ttf', mime: 'font/ttf', note: 'or application/font-sfnt-otf', noteZh: '或 application/font-sfnt-otf' },
	{ ext: 'otf', mime: 'font/otf' },
	{ ext: 'eot', mime: 'application/vnd.ms-fontobject' },
	{ ext: 'pdf', mime: 'application/pdf' },
	{ ext: 'zip', mime: 'application/zip' },
	{ ext: 'gz', mime: 'application/gzip' },
	{ ext: 'tar', mime: 'application/x-tar' },
	{ ext: '7z', mime: 'application/x-7z-compressed' },
	{ ext: 'rar', mime: 'application/vnd.rar' },
	{ ext: 'bz2', mime: 'application/x-bzip2' },
	{ ext: 'xz', mime: 'application/x-xz' },
	{ ext: 'doc', mime: 'application/msword' },
	{ ext: 'docx', mime: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' },
	{ ext: 'xls', mime: 'application/vnd.ms-excel' },
	{ ext: 'xlsx', mime: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' },
	{ ext: 'ppt', mime: 'application/vnd.ms-powerpoint' },
	{ ext: 'pptx', mime: 'application/vnd.openxmlformats-officedocument.presentationml.presentation' },
	{ ext: 'odt', mime: 'application/vnd.oasis.opendocument.text' },
	{ ext: 'ods', mime: 'application/vnd.oasis.opendocument.spreadsheet' },
	{ ext: 'wasm', mime: 'application/wasm' },
	{ ext: 'webmanifest', mime: 'application/manifest+json' },
	{ ext: 'yaml', mime: 'application/yaml', note: 'text/yaml also registered', noteZh: 'text/yaml 也已注册' },
	{ ext: 'yml', mime: 'application/yaml' },
	{ ext: 'toml', mime: 'application/toml' },
	{ ext: 'mid', mime: 'audio/midi' },
	{ ext: 'psd', mime: 'image/vnd.adobe.photoshop' },
	{ ext: 'ai', mime: 'application/postscript' },
	{ ext: 'eps', mime: 'application/postscript' },
	{ ext: 'rtf', mime: 'application/rtf' },
	{ ext: 'apk', mime: 'application/vnd.android.package-archive' },
	{ ext: 'iso', mime: 'application/x-iso9660-image' },
	{ ext: 'dmg', mime: 'application/x-apple-diskimage' },
	{ ext: 'deb', mime: 'application/vnd.debian.binary-package' },
	{ ext: 'rpm', mime: 'application/x-rpm' },
	{ ext: 'jar', mime: 'application/java-archive' },
	{ ext: 'bin', mime: 'application/octet-stream', note: 'the fallback for unknown bytes', noteZh: '未知字节的兜底类型' },
];
