// Well-known TCP/UDP port reference, consumed by the devtools/port-lookup tool.
// One entry per port (deduped); both-proto services use proto: "both".
export interface PortEntry {
	port: number;
	proto: 'TCP' | 'UDP' | 'both';
	service: string;
	serviceZh: string;
	note?: string;
	noteZh?: string;
}
export const PORTS: PortEntry[] = [
	{ port: 20, proto: 'TCP', service: 'FTP data', serviceZh: 'FTP 数据', note: 'active mode', noteZh: '主动模式' },
	{ port: 21, proto: 'TCP', service: 'FTP control', serviceZh: 'FTP 控制' },
	{ port: 22, proto: 'TCP', service: 'SSH / SFTP', serviceZh: 'SSH / SFTP', note: 'also SCP and Git over SSH', noteZh: '含 SCP 与 Git over SSH' },
	{ port: 23, proto: 'TCP', service: 'Telnet', serviceZh: 'Telnet', note: 'plaintext — never expose', noteZh: '明文传输——切勿暴露' },
	{ port: 25, proto: 'TCP', service: 'SMTP (server-to-server)', serviceZh: 'SMTP（服务器间）', note: 'client submission uses 587', noteZh: '客户端投递用 587' },
	{ port: 53, proto: 'both', service: 'DNS', serviceZh: 'DNS 域名解析' },
	{ port: 67, proto: 'UDP', service: 'DHCP server', serviceZh: 'DHCP 服务端' },
	{ port: 68, proto: 'UDP', service: 'DHCP client', serviceZh: 'DHCP 客户端' },
	{ port: 69, proto: 'UDP', service: 'TFTP', serviceZh: 'TFTP 简单文件传输' },
	{ port: 80, proto: 'TCP', service: 'HTTP', serviceZh: 'HTTP' },
	{ port: 88, proto: 'TCP', service: 'Kerberos', serviceZh: 'Kerberos 认证' },
	{ port: 110, proto: 'TCP', service: 'POP3', serviceZh: 'POP3 收信' },
	{ port: 119, proto: 'TCP', service: 'NNTP', serviceZh: 'NNTP 新闻组' },
	{ port: 123, proto: 'UDP', service: 'NTP', serviceZh: 'NTP 时间同步' },
	{ port: 137, proto: 'UDP', service: 'NetBIOS name', serviceZh: 'NetBIOS 名称服务' },
	{ port: 139, proto: 'TCP', service: 'NetBIOS session', serviceZh: 'NetBIOS 会话' },
	{ port: 143, proto: 'TCP', service: 'IMAP', serviceZh: 'IMAP 收信' },
	{ port: 161, proto: 'UDP', service: 'SNMP', serviceZh: 'SNMP 网络管理' },
	{ port: 179, proto: 'TCP', service: 'BGP', serviceZh: 'BGP 路由协议' },
	{ port: 194, proto: 'TCP', service: 'IRC', serviceZh: 'IRC 聊天' },
	{ port: 389, proto: 'TCP', service: 'LDAP', serviceZh: 'LDAP 目录' },
	{ port: 445, proto: 'TCP', service: 'SMB / CIFS', serviceZh: 'SMB / CIFS 文件共享' },
	{ port: 465, proto: 'TCP', service: 'SMTPS (implicit TLS)', serviceZh: 'SMTPS（隐式 TLS）' },
	{ port: 500, proto: 'UDP', service: 'IPsec IKE', serviceZh: 'IPsec IKE' },
	{ port: 514, proto: 'UDP', service: 'Syslog', serviceZh: 'Syslog 日志' },
	{ port: 515, proto: 'TCP', service: 'LPD printing', serviceZh: 'LPD 打印' },
	{ port: 587, proto: 'TCP', service: 'SMTP submission (STARTTLS)', serviceZh: 'SMTP 提交（STARTTLS）', note: 'the modern client port', noteZh: '现代客户端端口' },
	{ port: 631, proto: 'TCP', service: 'IPP / CUPS printing', serviceZh: 'IPP / CUPS 打印' },
	{ port: 636, proto: 'TCP', service: 'LDAPS', serviceZh: 'LDAPS（LDAP over TLS）' },
	{ port: 873, proto: 'TCP', service: 'rsync', serviceZh: 'rsync 同步' },
	{ port: 993, proto: 'TCP', service: 'IMAPS', serviceZh: 'IMAPS（IMAP over TLS）' },
	{ port: 995, proto: 'TCP', service: 'POP3S', serviceZh: 'POP3S（POP3 over TLS）' },
	{ port: 1080, proto: 'TCP', service: 'SOCKS proxy', serviceZh: 'SOCKS 代理' },
	{ port: 1194, proto: 'UDP', service: 'OpenVPN', serviceZh: 'OpenVPN' },
	{ port: 1521, proto: 'TCP', service: 'Oracle DB', serviceZh: 'Oracle 数据库' },
	{ port: 1723, proto: 'TCP', service: 'PPTP VPN', serviceZh: 'PPTP VPN' },
	{ port: 1900, proto: 'UDP', service: 'UPnP / SSDP', serviceZh: 'UPnP / SSDP', note: 'a classic LAN discovery + DDoS amplification source', noteZh: '局域网发现协议，也是 DDoS 放大反射的经典来源' },
	{ port: 2049, proto: 'TCP', service: 'NFS', serviceZh: 'NFS 网络文件系统' },
	{ port: 2082, proto: 'TCP', service: 'cPanel HTTP', serviceZh: 'cPanel 面板（HTTP）' },
	{ port: 2083, proto: 'TCP', service: 'cPanel HTTPS', serviceZh: 'cPanel 面板（HTTPS）' },
	{ port: 2375, proto: 'TCP', service: 'Docker API (unencrypted!)', serviceZh: 'Docker API（未加密！）', note: 'exposing 0.0.0.0:2375 = root to anyone', noteZh: '暴露 0.0.0.0:2375 等于送出 root' },
	{ port: 2376, proto: 'TCP', service: 'Docker API (TLS)', serviceZh: 'Docker API（TLS）' },
	{ port: 3128, proto: 'TCP', service: 'Squid proxy', serviceZh: 'Squid 代理' },
	{ port: 3260, proto: 'TCP', service: 'iSCSI', serviceZh: 'iSCSI 存储网络' },
	{ port: 3306, proto: 'TCP', service: 'MySQL / MariaDB', serviceZh: 'MySQL / MariaDB' },
	{ port: 3389, proto: 'TCP', service: 'RDP (Windows remote desktop)', serviceZh: 'RDP（Windows 远程桌面）', note: 'a top brute-force target — keep behind VPN', noteZh: '暴力破解头号目标——务必放在 VPN 后面' },
	{ port: 3690, proto: 'TCP', service: 'Subversion (SVN)', serviceZh: 'Subversion (SVN)' },
	{ port: 443, proto: 'TCP', service: 'HTTPS', serviceZh: 'HTTPS' },
	{ port: 5060, proto: 'both', service: 'SIP (VoIP)', serviceZh: 'SIP（VoIP 通话）' },
	{ port: 5061, proto: 'TCP', service: 'SIP over TLS', serviceZh: 'SIP over TLS' },
	{ port: 5353, proto: 'UDP', service: 'mDNS (Bonjour)', serviceZh: 'mDNS（Bonjour 发现）' },
	{ port: 5432, proto: 'TCP', service: 'PostgreSQL', serviceZh: 'PostgreSQL' },
	{ port: 5555, proto: 'TCP', service: 'ADB (Android debug)', serviceZh: 'ADB（安卓调试）' },
	{ port: 5601, proto: 'TCP', service: 'Kibana', serviceZh: 'Kibana 可视化' },
	{ port: 5672, proto: 'TCP', service: 'AMQP / RabbitMQ', serviceZh: 'AMQP / RabbitMQ 消息队列' },
	{ port: 5900, proto: 'TCP', service: 'VNC', serviceZh: 'VNC 远程桌面', note: 'display :0 = 5900, :1 = 5901, …', noteZh: '显示区 :0 对应 5900、:1 对应 5901……' },
	{ port: 5984, proto: 'TCP', service: 'CouchDB', serviceZh: 'CouchDB' },
	{ port: 6379, proto: 'TCP', service: 'Redis', serviceZh: 'Redis', note: 'unauthenticated by default — never expose', noteZh: '默认无鉴权——切勿暴露公网' },
	{ port: 6443, proto: 'TCP', service: 'Kubernetes API', serviceZh: 'Kubernetes API' },
	{ port: 6667, proto: 'TCP', service: 'IRC', serviceZh: 'IRC' },
	{ port: 7547, proto: 'TCP', service: 'TR-069 (ISP modem mgmt)', serviceZh: 'TR-069（运营商光猫管理）' },
	{ port: 8000, proto: 'TCP', service: 'HTTP alt (common dev)', serviceZh: 'HTTP 备用（常见于开发）' },
	{ port: 8080, proto: 'TCP', service: 'HTTP alt / proxies', serviceZh: 'HTTP 备用 / 代理' },
	{ port: 8443, proto: 'TCP', service: 'HTTPS alt', serviceZh: 'HTTPS 备用' },
	{ port: 8888, proto: 'TCP', service: 'HTTP alt / Jupyter', serviceZh: 'HTTP 备用 / Jupyter' },
	{ port: 9001, proto: 'TCP', service: 'Tor ORPort / various', serviceZh: 'Tor ORPort / 其他' },
	{ port: 9090, proto: 'TCP', service: 'Prometheus', serviceZh: 'Prometheus 监控' },
	{ port: 9200, proto: 'TCP', service: 'Elasticsearch', serviceZh: 'Elasticsearch', note: 'unauthenticated by default', noteZh: '默认无鉴权' },
	{ port: 11211, proto: 'TCP', service: 'Memcached', serviceZh: 'Memcached', note: 'a historical DDoS amplifier', noteZh: '历史上的 DDoS 放大器' },
	{ port: 27017, proto: 'TCP', service: 'MongoDB', serviceZh: 'MongoDB' },
	{ port: 25565, proto: 'TCP', service: 'Minecraft server', serviceZh: 'Minecraft 服务器' },
];
